[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [{ access = "read", path = "./" }]

[rpc_endpoints]
mezo_testnet = "${MEZO_TESTNET_RPC}"

[etherscan]
mezo_testnet = { key = "${MEZO_EXPLORER_KEY}", url = "https://explorer.test.mezo.org/api" }
